[build]
  command = "chmod +x scripts/netlify-build.sh && ./scripts/netlify-build.sh"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  NEXT_DISABLE_SOURCEMAPS = "true"
  NEXT_PUBLIC_NETLIFY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["public/**"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cdn.sanity.io; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://cdn.sanity.io; connect-src 'self' https://*.supabase.co https://*.sanity.io;" 